[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/public-quote"
  to = "/.netlify/functions/public-quote"
  status = 200

[[redirects]]
  from = "/api/public-driver-application"
  to = "/.netlify/functions/public-driver-application"
  status = 200

[[redirects]]
  from = "/api/invite-driver"
  to = "/.netlify/functions/invite-driver"
  status = 200

[[redirects]]
  from = "/api/create-checkout"
  to = "/.netlify/functions/create-checkout"
  status = 200

[[redirects]]
  from = "/api/send-payment-link"
  to = "/.netlify/functions/send-payment-link"
  status = 200

[[redirects]]
  from = "/api/send-invoice-email"
  to = "/.netlify/functions/send-invoice-email"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
