[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/create-checkout"
  to = "/.netlify/functions/create-checkout"
  status = 200

[[redirects]]
  from = "/api/send-payment-link"
  to = "/.netlify/functions/send-payment-link"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200